const ErrorResponse = require("../utils/errorResponse")

exports.handleOrder = async (req, res, next) => {
    try{

    }
    catch(err) {
        return new ErrorResponse("something went wrong")
    }
}